services:
  - type: web
    name: randomaccess-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/randomaccess-backend-0.0.1-SNAPSHOT.jar
envVars:
  - key: SPRING_DATASOURCE_URL
    value: jdbc:mysql://randomaccess-restapi-artvisuals.f.aivencloud.com:23067/defaultdb?ssl-mode=REQUIRED
  - key: SPRING_DATASOURCE_USERNAME
    value: avnadmin
  - key: SPRING_DATASOURCE_PASSWORD
    value: AVNS_yuuMnqg9kF3noNdhYb5
  - key: SPRING_PROFILES_ACTIVE
    value: default
